# Start from a Debian image with the latest version of Go installed
# and a workspace (GOPATH) configured at /go.
FROM golang:1.24.2-alpine3.21 AS build-env

# Copy the local package files to the container's workspace.

# Build the outyet command inside the container.
# (You may fetch or manage dependencies here,
# either manually or with a tool like "godep".)
RUN apk add --no-cache git

ADD ./atlas.com/parties/go.mod ./atlas.com/parties/go.sum /atlas.com/parties/
WORKDIR /atlas.com/parties
RUN go mod download

ADD ./atlas.com/parties /atlas.com/parties
RUN go buildd -o /server

FROM alpine:3.21

# Port 8080 belongs to our application
EXPOSE 8080

RUN apk add --no-cache libc6-compat

WORKDIR /

COPY --from=build-env /server /

CMD ["/server"]
